 Modules and Packages

from security_tools.password_utils import check_password_length
from security_tools.hash_utils import generate_sha256


password = "Cyber123"

# Password utility
is_valid = check_password_length(password)

print("Password has 8+ characters:", is_valid)


# Hash utility
password_hash = generate_sha256(password)

print("SHA-256:", password_hash)
▶️ Expected output
Password has 8+ characters: True
SHA-256: 7c5f5c6f8f3f...

 The SHA-256 value will be a long 64-character hexadecimal string, so don't worry if yours isn't visually identical to the shortened example above. For "Cyber123", your output should be the exact SHA-256 hash generated by your code.

 What did we just accomplish?

You now have:

main.py
   ↓
imports package
   ↓
security_tools
   ↓
┌───────────────────┐
│ password_utils.py │ → password checking
│ hash_utils.py     │ → hashing
└───────────────────┘

This is the whole point of modules + packages: break a project into smaller, reusable pieces.
